# Follow: https://github.com/dependabot/dependabot-core/issues/2165 for multi-schedule
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dependabot-updates"
    schedule:
      interval: "daily"
      time: "05:00"
    ignore:
      - dependency-name: "@types/node"
        versions: ["13", "14", "15", "16", "17"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
