# Follow: https://github.com/dependabot/dependabot-core/issues/2165 for multi-schedule
version: 2
updates:
  - package-ecosystem: "npm"
    directory: /
    schedule:
      interval: "daily"
      time: "05:00"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "lru-cache"
    labels:
      - "⚙️ dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "05:07"
    labels:
      - "⚙️ dependencies"
