name: Dependabot automerge

on:
  pull_request:

jobs:
  dependabot-automerge:
    permissions:
      pull-requests: write
      contents: write
    uses: matthieubosquet/workflows/.github/workflows/node-dependabot-automerge.yml@v0.5.0
