name: Test

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node: ["12", "14", "16"]
    steps:
      - uses: actions/checkout@v2
      - name: Runs on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci --ignore-scripts
      - run: npm run build
      - run: npm run test
